version: '3'
services:
  neo4j:
    image: neo4j:4.3.7
    hostname: neo4j
    container_name: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ./neo4j/plugins:/plugins
      - ./neo4j/data:/data
    environment:
      NEO4J_AUTH: neo4j/tmppassword # tmp
      NEO4J_dbms_logs_debug_level: DEBUG